name = "BayesianMethods"
uuid = "23af6a7e-9c29-46cc-a7b4-d8ac0872bf4c"
authors = ["Tim Übelhör <t.uebelhoer@irt.rwth-aachen.de>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
