name = "BayesianMethodsSoss"
uuid = "2050232e-2d88-4053-8f08-a69363a226d2"
authors = ["Tim Redick <t.redick@irt.rwth-aachen.de>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
MeasureBase = "fa1605e6-acd5-459c-a1e6-7e635759db14"
MeasureTheory = "eadaa1a4-d27c-401d-8699-e962e1bbc33b"
Soss = "8ce77f84-9b61-11e8-39ff-d17a774bf41c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
